Traceback (most recent call last):
  File "18.py", line 9, in <module>
    print(lista[i])
IndexError: list index out of range
